if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
  # define utility function for interacting with vterm on emacs
  function vterm_printf() {
    if [ -n "$TMUX" ]; then
        # Tell tmux to pass the escape sequences through
        # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
  }

  function vterm_prompt_end() {
      vterm_printf "51;A$(whoami)@$(hostname):$(pwd)"
  }

  function clear(){
      vterm_printf "51;Evterm-clear-scrollback";
      tput clear;
  }

  # If we are using starship, setup the vterm_prompt_end so that the current
  # directory gets updated everytime I change dirs on my terminal
  starship_precmd_user_func="vterm_prompt_end"
fi
