#!/usr/bin/env -S bash -xe

PROFILE="${1:-$USER}"

. $HOME/.nix-profile/etc/profile.d/nix.sh

nix build --impure ".#homeManagerConfigurations.$PROFILE.activationPackage" -o /tmp/guest-init-result # --show-trace
/tmp/guest-init-result/activate
