#!/bin/bash

nix-channel --remove nixpkgs
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
nix-channel --update

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "$DIR/.." || exit
git submodule init
git submodule update
sudo ln -s "$(pwd)/../hosts/$(hostname)/default.nix" "$HOME/.config/nixpkgs/home.nix"
popd || exit
